"""
Title: board_builder.py — Chess board SVG frame builder
Description:
    Generates SVG board frames for the game analysis page. Produces one SVG per ply,
    with engine arrow overlays (Stockfish + Lc0) and injected evaluation labels.
    Returns structured data for embedding in templates; HTML/JS rendering is handled
    by views and templates.

Changelog:
    2026-05-04 (#16): Rewrote to return frame data dict instead of HTML blob;
                      promoted _build_tier_map to module level for testability.
    2025-xx-xx:       Initial implementation with build_board_viewer_html.
"""

from __future__ import annotations

import io
import re

import chess
import chess.pgn
import chess.svg

from games.services import GameAnalysisData, MoveRow

_BOARD_COLORS = {
    "square light": "#F2E6D0",
    "square dark": "#4A8C62",
    "margin": "#1A1A1A",
    "coord": "#D4A843",
}

_SF_ARROW_COLORS = ["#D4A843CC", "#D4A84377", "#D4A84333"]
_LC0_ARROW_COLORS = ["#4A6E8ACC", "#4A6E8A77", "#4A6E8A33"]


def _build_tier_map(by_ply: dict[int, MoveRow], use_cp_equiv: bool) -> dict[int, list]:
    """
    Build a ply-indexed map of arrow tier entries for one engine's analysis.

    Params:
        by_ply (dict): Mapping of ply number → MoveRow from the engine.
        use_cp_equiv (bool): If True, use cp_equiv for scores (Lc0); else use arrow scores (SF).

    Returns:
        Dict mapping ply → list of {uci, score} dicts for arrow rendering.
    """
    result: dict[int, list] = {}
    for ply, row in by_ply.items():
        entries = []
        ucis = [row.arrow_uci, row.arrow_uci_2, row.arrow_uci_3]
        scores = [row.arrow_score_1, row.arrow_score_2, row.arrow_score_3]
        if use_cp_equiv:
            scores = [row.cp_equiv, None, None]
        for uci, score in zip(ucis, scores):
            if uci:
                entries.append({"uci": uci, "score": score})
        if entries:
            result[ply] = entries
    return result


def _inject_arrow_labels(svg: str, labels: list[dict], size: int, flipped: bool) -> str:
    """
    Inject evaluation score labels on top of move arrows in an SVG board.

    Params:
        svg (str): The SVG string generated by chess.svg.board.
        labels (list): List of {engine, label, from_sq, to_sq} dicts.
        size (int): Board size in pixels (used for coordinate mapping).
        flipped (bool): Whether the board is displayed from Black's perspective.

    Returns:
        SVG string with text overlay elements appended before </svg>.
    """
    if not labels or not svg:
        return svg
    _MARGIN = 15
    _SQ = 45

    def sq_to_px(sq: str) -> tuple[float, float]:
        """Convert algebraic square (e.g., 'e4') to pixel coordinates."""
        if not sq or len(sq) < 2:
            return (0.0, 0.0)
        try:
            f = ord(sq[0]) - ord("a")
            r = int(sq[1]) - 1
            if flipped:
                f = 7 - f
                r = 7 - r
            return (_MARGIN + (f + 0.5) * _SQ, _MARGIN + (7 - r + 0.5) * _SQ)
        except (ValueError, IndexError):
            return (0.0, 0.0)

    by_sq: dict[str, list[dict]] = {}
    for label_data in labels:
        to_sq = label_data.get("to_sq", "")
        if to_sq and label_data.get("label"):
            by_sq.setdefault(to_sq, []).append(label_data)

    font_size = 11
    line_h = font_size + 3
    text_elements: list[str] = []
    for to_sq, sq_labels in by_sq.items():
        cx, cy = sq_to_px(to_sq)
        base_y = cy - _SQ * 0.22
        n = len(sq_labels)
        start_y = base_y - (n - 1) * line_h / 2
        for idx, ld in enumerate(sq_labels):
            engine = str(ld.get("engine", "sf")).lower()
            fg = "#FFE082" if "sf" in engine else "#80CBC4"
            lx, ly = cx, start_y + idx * line_h
            text = str(ld.get("label", ""))
            text_elements.append(
                f'<rect x="{lx-18:.1f}" y="{ly-font_size+1:.1f}" width="36" height="{font_size+2}" rx="2" fill="#1A1A1A" fill-opacity="0.72" pointer-events="none"/>'
                f'<text x="{lx:.1f}" y="{ly:.1f}" text-anchor="middle" dominant-baseline="auto" font-size="{font_size}" font-weight="bold" font-family="monospace" fill="{fg}" pointer-events="none">{text}</text>'
            )

    if not text_elements:
        return svg
    return re.sub(r"</svg>", "\n".join(text_elements) + "\n</svg>", svg, count=1)


def build_board_frames(
    data: GameAnalysisData,
    size: int = 480,
    orientation: str = "white",
) -> dict:
    """
    Generate all SVG board frames for a game and return structured data for template rendering.

    Produces one frame per ply (including the start position at ply 0), with engine
    arrows and injected evaluation labels. Returns a dict suitable for JSON-encoding
    and embedding in the board partial template.

    Params:
        data (GameAnalysisData): Assembled game analysis data.
        size (int): Board SVG size in pixels (default 480).
        orientation (str): "white" or "black" perspective.

    Returns:
        Dict with keys:
            frames (list[str]): SVG strings, one per ply (index 0 = start position).
            arrow_labels_by_ply (dict): Ply → list of arrow label dicts.
            san_list (list[str]): SAN move strings in game order.
            total_frames (int): Number of frames (= number of moves + 1).
            top_player (str): Player name shown at top of board.
            top_sym (str): Chess piece symbol for top player.
            top_side (str): "White" or "Black" for top player.
            bottom_player (str): Player name shown at bottom.
            bottom_sym (str): Chess piece symbol for bottom player.
            bottom_side (str): "White" or "Black" for bottom player.
            has_sf (bool): Whether Stockfish analysis is present.
            has_lc0 (bool): Whether Lc0 analysis is present.
    """
    flipped = orientation == "black"
    game = chess.pgn.read_game(io.StringIO(data.pgn))
    if game is None:
        board = chess.Board()
        start_svg = chess.svg.board(board, size=size, flipped=flipped, colors=_BOARD_COLORS)
        return {
            "frames": [start_svg],
            "arrow_labels_by_ply": {},
            "san_list": [],
            "total_frames": 1,
            "top_player": data.black if not flipped else data.white,
            "top_sym": "♟" if not flipped else "♙",
            "top_side": "Black" if not flipped else "White",
            "bottom_player": data.white if not flipped else data.black,
            "bottom_sym": "♙" if not flipped else "♟",
            "bottom_side": "White" if not flipped else "Black",
            "has_sf": data.has_sf,
            "has_lc0": data.has_lc0,
        }

    board = game.board()
    start_ply_offset = board.ply()
    moves_played: list[chess.Move] = list(game.mainline_moves())

    sf_by_ply: dict[int, MoveRow] = {row.ply: row for row in data.moves}
    lc0_by_ply: dict[int, MoveRow] = (
        {row.ply: row for row in data.lc0_moves} if data.lc0_moves else {}
    )

    sf_tier_map = _build_tier_map(sf_by_ply, use_cp_equiv=False) if sf_by_ply else None
    lc0_tier_map = _build_tier_map(lc0_by_ply, use_cp_equiv=True) if lc0_by_ply else None

    sf_played: dict[int, float] = {
        ply: row.cp_eval for ply, row in sf_by_ply.items() if row.cp_eval is not None
    }
    lc0_played: dict[int, float] = {
        ply: row.cp_equiv for ply, row in lc0_by_ply.items() if row.cp_equiv is not None
    }

    san_list: list[str] = []
    arrow_labels_by_ply: dict[int, list] = {}
    frames: list[str] = []

    # Frame 0: start position
    frames.append(chess.svg.board(board, size=size, flipped=flipped, colors=_BOARD_COLORS))

    board = game.board()
    for ply_i, move in enumerate(moves_played, start=1):
        abs_ply = ply_i + start_ply_offset
        san_list.append(board.san(move))
        board.push(move)

        arrows: list[chess.svg.Arrow] = []

        def _add_arrows(
            tier_map: dict | None,
            played_scores: dict,
            colors: list[str],
            engine_prefix: str,
        ) -> None:
            """Append arrow objects and label data for one engine's top moves at this ply."""
            if tier_map is None:
                return
            tier_entries = tier_map.get(abs_ply) or tier_map.get(ply_i) or []
            scores = [e.get("score") for e in tier_entries]
            ucis = [e.get("uci", "") for e in tier_entries]

            played_score = played_scores.get(abs_ply) or played_scores.get(ply_i)
            base = scores[0] if scores and scores[0] is not None else None

            for i, uci in enumerate(ucis):
                if not (uci and len(uci) >= 4):
                    continue
                try:
                    rgba = colors[i] if i < len(colors) else colors[-1]
                    arrows.append(
                        chess.svg.Arrow(
                            chess.parse_square(uci[:2]),
                            chess.parse_square(uci[2:4]),
                            color=rgba,
                        )
                    )
                    score = scores[i] if i < len(scores) else None
                    label = ""
                    if played_score is not None and score is not None:
                        gain = float(score) - float(played_score)
                        if "lc0" in engine_prefix.lower():
                            bps = int(round((gain / 100.0) * 4))
                            label = f"{bps:+d}%" if bps != 0 else "±0%"
                        else:
                            label = f"{int(round(gain)):+d}"
                    elif base is not None and score is not None and i > 0:
                        gap = float(base) - float(score)
                        if "lc0" in engine_prefix.lower():
                            bps = int(round((gap / 100.0) * 4))
                            label = f"{bps:+d}%" if bps != 0 else "±0%"
                        else:
                            label = f"{int(round(gap)):+d}"
                    if label:
                        arrow_labels_by_ply.setdefault(ply_i, []).append(
                            {
                                "engine": engine_prefix.lower(),
                                "label": label,
                                "from_sq": uci[:2],
                                "to_sq": uci[2:4],
                            }
                        )
                except ValueError:
                    pass

        _add_arrows(sf_tier_map, sf_played, _SF_ARROW_COLORS, "sf")
        _add_arrows(lc0_tier_map, lc0_played, _LC0_ARROW_COLORS, "lc0")

        svg = chess.svg.board(
            board,
            size=size,
            lastmove=move,
            arrows=arrows,
            flipped=flipped,
            colors=_BOARD_COLORS,
        )
        svg = _inject_arrow_labels(svg, arrow_labels_by_ply.get(ply_i, []), size, flipped)
        frames.append(svg)

    top_player = data.black if not flipped else data.white
    top_sym = "♟" if not flipped else "♙"
    top_side = "Black" if not flipped else "White"
    bottom_player = data.white if not flipped else data.black
    bottom_sym = "♙" if not flipped else "♟"
    bottom_side = "White" if not flipped else "Black"

    return {
        "frames": frames,
        "arrow_labels_by_ply": arrow_labels_by_ply,
        "san_list": san_list,
        "total_frames": len(frames),
        "top_player": top_player,
        "top_sym": top_sym,
        "top_side": top_side,
        "bottom_player": bottom_player,
        "bottom_sym": bottom_sym,
        "bottom_side": bottom_side,
        "has_sf": data.has_sf,
        "has_lc0": data.has_lc0,
    }
