"""
Title: board_builder.py — Chess board SVG frame builder
Description:
    Generates SVG board frames for the game analysis page. Produces one SVG per ply,
    with engine arrow overlays (Stockfish + Lc0) and injected evaluation labels.
    Returns structured data for embedding in templates; HTML/JS rendering is handled
    by views and templates.

Changelog:
    2026-05-04 (#16): Rewrote to return frame data dict instead of HTML blob;
                      promoted _build_tier_map to module level for testability.
    2025-xx-xx:       Initial implementation with build_board_viewer_html.
"""

from __future__ import annotations

import io
import re

import chess
import chess.pgn
import chess.svg

from games.services import GameAnalysisData, MoveRow

_BOARD_COLORS = {
    "square light": "#F2E6D0",
    "square dark": "#4A8C62",
    "margin": "#1A1A1A",
    "coord": "#D4A843",
}

_SF_ARROW_COLORS = ["#D4A843CC", "#D4A84377", "#D4A84333"]
_LC0_ARROW_COLORS = ["#4A6E8ACC", "#4A6E8A77", "#4A6E8A33"]


def _build_tier_map(by_ply: dict[int, MoveRow], use_cp_equiv: bool) -> dict[int, list]:
    """
    Build a ply-indexed map of arrow tier entries for one engine's analysis.

    Params:
        by_ply (dict): Mapping of ply number → MoveRow from the engine.
        use_cp_equiv (bool): If True, use cp_equiv for scores (Lc0); else use arrow scores (SF).

    Returns:
        Dict mapping ply → list of {uci, score} dicts for arrow rendering.
    """
    result: dict[int, list] = {}
    for ply, row in by_ply.items():
        entries = []
        ucis = [row.arrow_uci, row.arrow_uci_2, row.arrow_uci_3]
        scores = [row.arrow_score_1, row.arrow_score_2, row.arrow_score_3]
        if use_cp_equiv:
            scores = [row.cp_equiv, None, None]
        for uci, score in zip(ucis, scores):
            if uci:
                entries.append({"uci": uci, "score": score})
        if entries:
            result[ply] = entries
    return result


def _inject_arrow_ids(svg: str, colors_in_order: list[str]) -> str:
    """
    Inject data-arrow-index attributes to arrows in the SVG based on their color order.
    
    Params:
        svg (str): The SVG string with arrows.
        colors_in_order (list): List of arrow colors in the order they appear (e.g., ["#D4A843CC", "#D4A84377", ...])
    
    Returns:
        SVG string with data-arrow-index attributes added to arrow elements.
    """
    if not svg or not colors_in_order:
        return svg
    
    arrow_index = 0
    for color in colors_in_order:
        # Extract just the RGB part (first 7 chars) for matching
        hex_color = color[:7] if len(color) >= 7 else color
        
        # Match line or polygon tags with this color in stroke or fill attribute
        # Using a simple pattern that finds unindexed arrows with matching color
        pattern = rf'<(line|polygon)([^>]*(?:stroke|fill)=["\']?{re.escape(hex_color)}[^>]*)(?!\s+data-arrow-index)'
        replacement = rf'<\1\2 data-arrow-index="{arrow_index}"'
        
        svg = re.sub(pattern, replacement, svg, count=1)
        arrow_index += 1
    
    return svg


def _inject_arrow_labels(svg: str, labels: list[dict], size: int, flipped: bool) -> str:
    """
    Inject evaluation score labels on arrow bodies in an SVG board.
    Detects and prevents label overlaps by offsetting labels perpendicularly.

    Params:
        svg (str): The SVG string generated by chess.svg.board.
        labels (list): List of {engine, label, from_sq, to_sq} dicts.
        size (int): Board size in pixels (used for coordinate mapping).
        flipped (bool): Whether the board is displayed from Black's perspective.

    Returns:
        SVG string with text overlay elements appended before </svg>.
    """
    if not labels or not svg:
        return svg
    _MARGIN = 15
    _SQ = 45
    _LABEL_WIDTH = 36
    _LABEL_HEIGHT = 14
    _OFFSET_DISTANCE = 20  # Distance to offset overlapping labels

    # Map engine to primary arrow color (opaque version for labels)
    _ENGINE_COLORS = {
        "sf": "#D4A843",
        "lc0": "#4A6E8A",
    }

    def sq_to_px(sq: str) -> tuple[float, float]:
        """Convert algebraic square (e.g., 'e4') to pixel coordinates."""
        if not sq or len(sq) < 2:
            return (0.0, 0.0)
        try:
            f = ord(sq[0]) - ord("a")
            r = int(sq[1]) - 1
            if flipped:
                f = 7 - f
                r = 7 - r
            return (_MARGIN + (f + 0.5) * _SQ, _MARGIN + (7 - r + 0.5) * _SQ)
        except (ValueError, IndexError):
            return (0.0, 0.0)

    def rects_overlap(r1: dict, r2: dict) -> bool:
        """Check if two rectangles overlap (with 2px padding)."""
        padding = 2
        return not (
            r1["right"] + padding < r2["left"]
            or r2["right"] + padding < r1["left"]
            or r1["bottom"] + padding < r2["top"]
            or r2["bottom"] + padding < r1["top"]
        )

    def get_rect(cx: float, cy: float, font_size: int) -> dict:
        """Get bounding rect for a label at position (cx, cy)."""
        return {
            "left": cx - _LABEL_WIDTH / 2,
            "right": cx + _LABEL_WIDTH / 2,
            "top": cy - font_size + 1,
            "bottom": cy + _LABEL_HEIGHT / 2,
        }

    font_size = 11
    
    # First pass: collect label data with initial positions
    label_data_list: list[dict] = []
    for ld in labels:
        from_sq = ld.get("from_sq", "")
        to_sq = ld.get("to_sq", "")
        if not (from_sq and to_sq and ld.get("label")):
            continue
        
        try:
            x1, y1 = sq_to_px(from_sq)
            x2, y2 = sq_to_px(to_sq)
            if (x1, y1) == (0.0, 0.0) or (x2, y2) == (0.0, 0.0):
                continue
            
            # Position label at midpoint of arrow body
            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2
            
            engine = str(ld.get("engine", "sf")).lower()
            text = str(ld.get("label", ""))
            
            label_data_list.append({
                "cx": cx,
                "cy": cy,
                "engine": engine,
                "text": text,
                "dx": 0,  # offset x
                "dy": 0,  # offset y
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "arrow_index": ld.get("arrow_index", -1),
                "from_sq": from_sq,
                "to_sq": to_sq,
            })
        except (ValueError, IndexError):
            pass
    
    # Second pass: detect and resolve overlaps
    for i, label_i in enumerate(label_data_list):
        rect_i = get_rect(label_i["cx"] + label_i["dx"], label_i["cy"] + label_i["dy"], font_size)
        
        for j in range(i + 1, len(label_data_list)):
            label_j = label_data_list[j]
            rect_j = get_rect(label_j["cx"] + label_j["dx"], label_j["cy"] + label_j["dy"], font_size)
            
            if rects_overlap(rect_i, rect_j):
                # Calculate perpendicular direction to arrow i
                dx = label_i["x2"] - label_i["x1"]
                dy = label_i["y2"] - label_i["y1"]
                dist = (dx**2 + dy**2) ** 0.5
                if dist > 0:
                    # Perpendicular vector (rotate 90 degrees)
                    perp_x = -dy / dist
                    perp_y = dx / dist
                else:
                    perp_x, perp_y = 1, 0
                
                # Offset labels in opposite directions along perpendicular
                label_i["dx"] -= perp_x * _OFFSET_DISTANCE / 2
                label_i["dy"] -= perp_y * _OFFSET_DISTANCE / 2
                label_j["dx"] += perp_x * _OFFSET_DISTANCE / 2
                label_j["dy"] += perp_y * _OFFSET_DISTANCE / 2
                
                # Update rect_i for next iteration
                rect_i = get_rect(label_i["cx"] + label_i["dx"], label_i["cy"] + label_i["dy"], font_size)

    # Third pass: render labels with final positions
    text_elements: list[str] = []
    for ld in label_data_list:
        cx = ld["cx"] + ld["dx"]
        cy = ld["cy"] + ld["dy"]
        fg = _ENGINE_COLORS.get(ld["engine"], "#FFE082")
        
        # Create descriptive title for tooltip
        engine_name = "Stockfish" if ld["engine"] == "sf" else "Lc0"
        unit = "cp" if ld["engine"] == "sf" else "win%"
        title = f"{engine_name}: suggested move gain ({unit})"
        
        text_elements.append(
            f'<g class="arrow-label" data-engine="{ld["engine"]}" data-from-sq="{ld.get("from_sq", "")}" data-to-sq="{ld.get("to_sq", "")}" style="display:none" pointer-events="none">'
            f'<title>{title}</title>'
            f'<rect x="{cx-_LABEL_WIDTH/2:.1f}" y="{cy-font_size+1:.1f}" width="{_LABEL_WIDTH}" height="{font_size+2}" rx="2" fill="#1A1A1A" fill-opacity="0.72"/>'
            f'<text x="{cx:.1f}" y="{cy:.1f}" text-anchor="middle" dominant-baseline="auto" font-size="{font_size}" font-weight="bold" font-family="monospace" fill="{fg}">{ld["text"]}</text>'
            f'</g>'
        )

    if not text_elements:
        return svg
    return re.sub(r"</svg>", "\n".join(text_elements) + "\n</svg>", svg, count=1)


def build_board_frames(
    data: GameAnalysisData,
    size: int = 480,
    orientation: str = "white",
) -> dict:
    """
    Generate all SVG board frames for a game and return structured data for template rendering.

    Produces one frame per ply (including the start position at ply 0), with engine
    arrows and injected evaluation labels. Returns a dict suitable for JSON-encoding
    and embedding in the board partial template.

    Params:
        data (GameAnalysisData): Assembled game analysis data.
        size (int): Board SVG size in pixels (default 480).
        orientation (str): "white" or "black" perspective.

    Returns:
        Dict with keys:
            frames (list[str]): SVG strings, one per ply (index 0 = start position).
            arrow_labels_by_ply (dict): Ply → list of arrow label dicts.
            san_list (list[str]): SAN move strings in game order.
            total_frames (int): Number of frames (= number of moves + 1).
            top_player (str): Player name shown at top of board.
            top_sym (str): Chess piece symbol for top player.
            top_side (str): "White" or "Black" for top player.
            bottom_player (str): Player name shown at bottom.
            bottom_sym (str): Chess piece symbol for bottom player.
            bottom_side (str): "White" or "Black" for bottom player.
            has_sf (bool): Whether Stockfish analysis is present.
            has_lc0 (bool): Whether Lc0 analysis is present.
    """
    flipped = orientation == "black"
    game = chess.pgn.read_game(io.StringIO(data.pgn))
    if game is None:
        board = chess.Board()
        start_svg = chess.svg.board(board, size=size, flipped=flipped, colors=_BOARD_COLORS)
        return {
            "frames": [start_svg],
            "arrow_labels_by_ply": {},
            "san_list": [],
            "total_frames": 1,
            "top_player": data.black if not flipped else data.white,
            "top_sym": "♟" if not flipped else "♙",
            "top_side": "Black" if not flipped else "White",
            "bottom_player": data.white if not flipped else data.black,
            "bottom_sym": "♙" if not flipped else "♟",
            "bottom_side": "White" if not flipped else "Black",
            "has_sf": data.has_sf,
            "has_lc0": data.has_lc0,
        }

    board = game.board()
    start_ply_offset = board.ply()
    moves_played: list[chess.Move] = list(game.mainline_moves())

    sf_by_ply: dict[int, MoveRow] = {row.ply: row for row in data.moves}
    lc0_by_ply: dict[int, MoveRow] = (
        {row.ply: row for row in data.lc0_moves} if data.lc0_moves else {}
    )

    sf_tier_map = _build_tier_map(sf_by_ply, use_cp_equiv=False) if sf_by_ply else None
    lc0_tier_map = _build_tier_map(lc0_by_ply, use_cp_equiv=True) if lc0_by_ply else None

    sf_played: dict[int, float] = {
        ply: row.cp_eval for ply, row in sf_by_ply.items() if row.cp_eval is not None
    }
    lc0_played: dict[int, float] = {
        ply: row.cp_equiv for ply, row in lc0_by_ply.items() if row.cp_equiv is not None
    }

    san_list: list[str] = []
    arrow_labels_by_ply: dict[int, list] = {}
    frames: list[str] = []

    # Frame 0: start position
    frames.append(chess.svg.board(board, size=size, flipped=flipped, colors=_BOARD_COLORS))

    board = game.board()
    arrow_index = 0  # Global counter for arrow indices
    for ply_i, move in enumerate(moves_played, start=1):
        abs_ply = ply_i + start_ply_offset
        san_list.append(board.san(move))
        is_white_move = board.turn == chess.WHITE
        board.push(move)

        arrows: list[chess.svg.Arrow] = []

        def _add_arrows(
            tier_map: dict | None,
            played_scores: dict,
            colors: list[str],
            engine_prefix: str,
            is_white: bool = is_white_move,
        ) -> None:
            """Append arrow objects and label data for one engine's top moves at this ply.

            arrow_score_1/2/3 are stored mover-perspective (positive = good for mover).
            cp_eval is stored white-relative (positive = good for White).
            We convert cp_eval to mover-perspective before computing gain so that the
            label always shows how many centipawns the suggested move improves on the
            played move from the active player's point of view.
            """
            nonlocal arrow_index
            if tier_map is None:
                return
            tier_entries = tier_map.get(abs_ply) or tier_map.get(ply_i) or []
            scores = [e.get("score") for e in tier_entries]
            ucis = [e.get("uci", "") for e in tier_entries]

            played_score_white_rel = played_scores.get(abs_ply) or played_scores.get(ply_i)
            # Convert white-relative cp_eval to mover-perspective to match arrow_score convention.
            if played_score_white_rel is not None:
                played_mover = float(played_score_white_rel) if is_white else -float(played_score_white_rel)
            else:
                played_mover = None
            base = scores[0] if scores and scores[0] is not None else None

            for i, uci in enumerate(ucis):
                if not (uci and len(uci) >= 4):
                    continue
                try:
                    rgba = colors[i] if i < len(colors) else colors[-1]
                    arrows.append(
                        chess.svg.Arrow(
                            chess.parse_square(uci[:2]),
                            chess.parse_square(uci[2:4]),
                            color=rgba,
                        )
                    )
                    score = scores[i] if i < len(scores) else None
                    label = ""
                    if played_mover is not None and score is not None:
                        # Both are mover-perspective: positive gain = better for the mover.
                        gain = float(score) - played_mover
                        if "lc0" in engine_prefix.lower():
                            bps = int(round((gain / 100.0) * 4))
                            label = f"{bps:+d}% W" if bps != 0 else "±0% W"
                        else:
                            label = f"{int(round(gain)):+d}cp"
                    elif base is not None and score is not None and i > 0:
                        # No played move data: show how much worse this arrow is vs the best.
                        gap = float(score) - float(base)
                        if "lc0" in engine_prefix.lower():
                            bps = int(round((gap / 100.0) * 4))
                            label = f"{bps:+d}% W" if bps != 0 else "±0% W"
                        else:
                            label = f"{int(round(gap)):+d}cp"
                    if label:
                        arrow_labels_by_ply.setdefault(ply_i, []).append(
                            {
                                "engine": engine_prefix.lower(),
                                "label": label,
                                "from_sq": uci[:2],
                                "to_sq": uci[2:4],
                                "arrow_index": arrow_index,
                            }
                        )
                        arrow_index += 1
                except ValueError:
                    pass

        _add_arrows(sf_tier_map, sf_played, _SF_ARROW_COLORS, "sf")
        _add_arrows(lc0_tier_map, lc0_played, _LC0_ARROW_COLORS, "lc0")

        svg = chess.svg.board(
            board,
            size=size,
            lastmove=move,
            arrows=arrows,
            flipped=flipped,
            colors=_BOARD_COLORS,
        )
        
        # Inject arrow indices based on the order of arrows added
        arrow_colors_in_order = []
        for arrow in arrows:
            arrow_colors_in_order.append(arrow.color)
        if arrow_colors_in_order:
            svg = _inject_arrow_ids(svg, arrow_colors_in_order)
        
        # Inject arrow labels
        labels_for_ply = arrow_labels_by_ply.get(ply_i, [])
        if labels_for_ply:
            svg = _inject_arrow_labels(svg, labels_for_ply, size, flipped)
        
        frames.append(svg)

    top_player = data.black if not flipped else data.white
    top_sym = "♟" if not flipped else "♙"
    top_side = "Black" if not flipped else "White"
    bottom_player = data.white if not flipped else data.black
    bottom_sym = "♙" if not flipped else "♟"
    bottom_side = "White" if not flipped else "Black"

    return {
        "frames": frames,
        "arrow_labels_by_ply": arrow_labels_by_ply,
        "san_list": san_list,
        "total_frames": len(frames),
        "top_player": top_player,
        "top_sym": top_sym,
        "top_side": top_side,
        "bottom_player": bottom_player,
        "bottom_sym": bottom_sym,
        "bottom_side": bottom_side,
        "has_sf": data.has_sf,
        "has_lc0": data.has_lc0,
    }
